# Generated by Django 2.2.6 on 2020-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdictionaryword',
            name='pinyin',
            field=models.CharField(default='', max_length=16),
        ),
    ]
