# Generated by Django 2.2.6 on 2020-08-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataparser', '0002_customdictionaryword_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdictionaryword',
            name='freq',
            field=models.IntegerField(default=1),
        ),
    ]
