FROM python:3.7
WORKDIR /usr/src/docker-django
RUN pip3 install --upgrade setuptools pip


RUN pip3 install tensorflow
RUN pip3 install tensorflow_datasets

COPY . .
RUN pip3 install -r requirements.txt

RUN pip3 install psycopg2-binary
RUN pip3 install websocket
RUN pip3 install websocket-client
RUN pip3 install zhconv
RUN pip3 install xlwt
RUN pip3 install django-import-export


EXPOSE 8000
CMD [ "python3", "manage.py", "tcpsocket" ]

