# Generated by Django 2.2.6 on 2019-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=96)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blockword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=96)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whiteword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='goodsentence',
            index=models.Index(fields=['-date'], name='service_goo_date_6fa73a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedsentence',
            index=models.Index(fields=['-date'], name='service_blo_date_42cb59_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedsentence',
            index=models.Index(fields=['status'], name='service_blo_status_f79b19_idx'),
        ),
    ]
