# Generated by Django 2.2.6 on 2020-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200507_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=64)),
                ('type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('model', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['-date'], name='service_tex_date_c71aac_idx'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['status'], name='service_tex_status_08fc59_idx'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['model'], name='service_tex_model_840e44_idx'),
        ),
    ]
