# Generated by Django 2.2.6 on 2020-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200507_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNicknameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=63)),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='changenicknamerequest',
            index=models.Index(fields=['status'], name='service_cha_status_8e586a_idx'),
        ),
    ]
