# Generated by Django 2.2.6 on 2021-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200620_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPinyinBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('pinyin', models.CharField(max_length=64)),
                ('type', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='dynamicpinyinblock',
            index=models.Index(fields=['type'], name='service_dyn_type_8f3e13_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicpinyinblock',
            index=models.Index(fields=['-date'], name='service_dyn_date_c2bb13_idx'),
        ),
    ]
