# Generated by Django 2.2.6 on 2022-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20211213_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAlertWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
