# Generated by Django 3.0.7 on 2023-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_dynamicalertwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicNicknamePinyinBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('pinyin', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='dynamicnicknamepinyinblock',
            index=models.Index(fields=['-date'], name='service_dyn_date_85b5ec_idx'),
        ),
    ]
