# Generated by Django 3.0.7 on 2025-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20230216_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAlphaNumBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
