# Generated by Django 2.2.6 on 2019-12-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('chinese', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('chinese', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.ManyToManyField(to='ai.AbstractMeaning')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.Language')),
                ('part', models.ManyToManyField(to='ai.PartOfSpeech')),
            ],
        ),
        migrations.CreateModel(
            name='SoundVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin', models.CharField(max_length=65)),
                ('type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('vocabulary', models.ManyToManyField(to='ai.Vocabulary')),
            ],
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['language'], name='ai_vocabula_languag_1c71d8_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['status'], name='ai_vocabula_status_a8359b_idx'),
        ),
        migrations.AddIndex(
            model_name='soundvocabulary',
            index=models.Index(fields=['status'], name='ai_soundvoc_status_1fe6be_idx'),
        ),
    ]
