# Generated by Django 2.2.6 on 2019-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='similarity',
            field=models.ManyToManyField(related_name='_vocabulary_similarity_+', to='ai.Vocabulary'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='context',
            field=models.CharField(max_length=255),
        ),
    ]
