# Generated by Django 2.2.6 on 2020-01-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='is_common',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='meaning',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
