# Generated by Django 2.2.6 on 2020-01-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20200107_1343'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='soundvocabulary',
            name='ai_soundvoc_status_1fe6be_idx',
        ),
        migrations.AddIndex(
            model_name='soundvocabulary',
            index=models.Index(fields=['pinyin', 'status'], name='ai_soundvoc_pinyin_75cdb9_idx'),
        ),
    ]
