# Generated by Django 2.2.6 on 2020-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_digitalvocabulary_pinyin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='digitalvocabulary',
            name='ai_digitalv_status_05b869_idx',
        ),
        migrations.RemoveIndex(
            model_name='soundvocabulary',
            name='ai_soundvoc_status_4ea150_idx',
        ),
        migrations.AddIndex(
            model_name='digitalvocabulary',
            index=models.Index(fields=['digits'], name='ai_digitalv_digits_ab9805_idx'),
        ),
        migrations.AddIndex(
            model_name='soundvocabulary',
            index=models.Index(fields=['pinyin'], name='ai_soundvoc_pinyin_629fc6_idx'),
        ),
    ]
