# Generated by Django 2.2.6 on 2020-01-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20200116_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin', models.CharField(default='', max_length=65)),
                ('type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddIndex(
            model_name='newvocabulary',
            index=models.Index(fields=['pinyin'], name='ai_newvocab_pinyin_197844_idx'),
        ),
    ]
