# Generated by Django 2.2.6 on 2020-08-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_auto_20200817_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooksentense',
            name='keypoint',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='textbooksentense',
            name='reason',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='textbooksentense',
            index=models.Index(fields=['reason'], name='ai_textbook_reason_c5f07e_idx'),
        ),
        migrations.AddIndex(
            model_name='textbooksentense',
            index=models.Index(fields=['weight'], name='ai_textbook_weight_c2771e_idx'),
        ),
    ]
