# Generated by Django 2.2.6 on 2020-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_auto_20200818_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='is_common',
        ),
        migrations.AddField(
            model_name='digitalvocabulary',
            name='freq',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='newvocabulary',
            name='freq',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='soundvocabulary',
            name='freq',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='freq',
            field=models.IntegerField(default=1),
        ),
    ]
